# Generated by Django 4.2.3 on 2023-08-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmRating", "0002_remove_film_rating_alter_film_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
