# Generated by Django 4.2.3 on 2023-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmRating', '0004_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
